### ISSUE TITLE
session.save_path for site playbook on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Camisa** [rillip3/lamp#10]
I noticed the /etc/php5/apache2/php.ini has a typo with regard to the session.save_path. For some reason, "session_save_path" is there instead of session.save_path. If "session_save_path" is used as if it were the correct variable, than its value is not reflected in a PHP info page. Only when the variable is renamed to session.save_path will its value be honored.

**Comment by rillip3** [comment]
This looks like a sloppy search/replace done in the past. Session_save_path is in fact the correct identifier for an Ansible variable for this playbook, but obviously is not valid in the context you're referencing. Should have a fix shortly.

**Comment by rillip3** [comment]
Fixed in above PR, please reopen if any further issues are identified.
