### ISSUE TITLE
mysql_password is not complex

### ISSUE THREAD

**Issue by joeashcraft** [rillip3/lamp#12]
We should use more complex passwords for the mysql_password, which is used for MySQL user's 'root' and 'holland'. This can easily be accomplished by removing the "chars" parameter.

We've limited the password generation to only letters (both upper and lower) and digits by using the "chars" parameter.
The default password generation includes upper- and lower-case letters, digits, and 5 punctuation marks (". , : - _"). Removing the "chars" parameter will cause Ansible to generate more complex passwords than we're creating now.

**Comment by rillip3** [comment]
Chars was specifically added because quotation marks were being randomly generated. One of the other automation pieces - I think the Holland plugin - was not sanitizing those properly and causing issues. This also kept the password in line with what Orchestration is/was generating.
