### ISSUE TITLE
Debian 8 (Jessie) - Module authz_default does not exist!

### ISSUE THREAD

**Issue by Camisa** [rillip3/lamp#7]
The site playbook fails on Debian 8 (Jessie) at the authz_default task.
[Jessie-authz_default.txt](https://github.com/rillip3/lamp/files/275728/Jessie-authz_default.txt)

**Comment by Camisa** [comment]
Also discovered Ubuntu 16.04 LTS (Xenial Xerus) fails on the same authz_default task.
[Xenial Xerus-authz_default.txt](https://github.com/rillip3/lamp/files/275740/Xenial.Xerus-authz_default.txt)

**Comment by rillip3** [comment]
Can no longer duplicate after the above pull, please report any new incidents as a new issue.
