### ISSUE TITLE
Duplicate text/html MIME type with nginx playbook

### ISSUE THREAD

**Issue by Camisa** [rillip3/lamp#9]
The Nginx v1.10.0 deployment includes an /etc/nginx/mime.types with the "text/html" MIME type declared within it.

    The provided /etc/nginx/nginx.conf duplicates this on line 30 in the gzip_types declaration, leading to the following warning.

        [warn] 30382#30382: duplicate MIME type "text/html" in /etc/nginx/nginx.conf:30

    Removing "text/html" from the gzip_types declaration permits Nginx to start without any warnings.

Kind Regards,
-Camisa

**Comment by rillip3** [comment]
According to nginx documentation (https://www.nginx.com/resources/admin-guide/compression-and-decompression/) explicitly setting text/html is not needed for gzip, so it can be removed without change to functionality. Should have a pull shortly.

**Comment by rillip3** [comment]
Fixed in above PR, please reopen issue if any related issues found
